name: Go

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          mkdir dist
          go build -o dist/mpd-lrc

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/mpd-lrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
